[connection]
server = "https://matrix.org/"
username = "myrustix"
password = ""

[bot]
display_name = "rustix"
prefix = "!"
rooms = ["rustixtesting"]
admins = ["@me:matrix.org"]
ignore = ["@bot1:matrix.my.domain.com", "@bot2:matrix.my.domain.com"]

[services]
[services.try_file]
directory = "/usr/share/rustix"

[services.csv_quote]
file = "csv_quotes.csv"
